name: Build:Master
on:
    workflow_dispatch:
    push:
        branches:
            - master
            

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

     - name: Build and Push
              uses: actions/checkout@v2

            - name: Node Setup
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'

            - name: NPM Install
              run: npm install

            - name: Webpack Build Bundles
              run: npm run build

            - name: Git Push /Public
              run: |
                  git config --global user.name 'github-actions'
                  git config --global user.email 'actions@users.noreply.github.com'
                  mv .git ./public
                  cd ./public
                  git checkout -b bundle
                  git commit -am "build-$(date)"
                  git push -u -f origin bundle
            
            - name: Server Webhook
              run: curl https://example.com/gitpull.php
